### ISSUE TITLE
conv_transpose2d parameter order problem

### ISSUE THREAD

**Issue by pierreosselin** [IntelLabs/bayesian-torch#13]
https://github.com/IntelLabs/bayesian-torch/blob/f6f516e9b3721466aa0036c735475a421cc3ce80/bayesian_torch/layers/variational_layers/conv_variational.py#L784-L786

![image](https://user-images.githubusercontent.com/52010943/168824523-62da883f-091b-46fb-b358-b049e5a0998a.png)

When I try to convert a deterministic autoencoder into a bayesian one with a ConvTranspose2d layer I get the error "Exception has occurred: TypeError
conv_transpose2d(): argument 'groups' (position 7) must be int, not tuple" which I suspect comes from self.dilation and self.group which are swaped.

**Comment by ranganathkrishnan** [comment]
@pierreosselin can you check how you are getting model output in your code? If return_kl flag is True (by default), the forward function returns a tuple (output and kl) - https://github.com/IntelLabs/bayesian-torch/blob/f6f516e9b3721466aa0036c735475a421cc3ce80/bayesian_torch/layers/variational_layers/conv_variational.py#L793

**Comment by ranganathkrishnan** [comment]
closing the issue due to no response from the user.

**Comment by SoyedTuhinAhmed** [comment]
I am having the same issue and return_kl flag is False

**Comment by rameshamurtaza** [comment]
I am having the same Issue, pls suggest what can be wrong
