### ISSUE TITLE
Error in trans_conv2d when model is reparametrized 

### ISSUE THREAD

**Issue by rameshamurtaza** [IntelLabs/bayesian-torch#21]
conv_transpose2d(): argument 'groups' (position 7) must be int, not tuple

I used this command to convert my model to bnn  (const_bnn_prior_parameters) and now getting this error

**Comment by Spiffical** [comment]
I believe I found the error. In line 812 of `bayesian_torch/layers/variational_layers/conv_variational.py` the `F.conv_transpose2d` function is being called as:

```
out = F.conv_transpose2d(input, weight, bias, self.stride,
                                 self.padding, self.output_padding,
                                 self.dilation, self.groups)
```

i.e. the order is dilation then groups, whereas as seen in https://pytorch.org/docs/stable/generated/torch.nn.functional.conv_transpose2d.html , the order should be groups then dilation:

```
out = F.conv_transpose2d(input, weight, bias, self.stride,
                                 self.padding, self.output_padding,
                                 self.groups, self.dilation)
```

**Comment by ranganathkrishnan** [comment]
Fixed. commit 97ba16ad044022035ba22b17aa279f2d389129eb
