### ISSUE TITLE
local variable 'kl' referenced before assignment when using flipout in dnn_to_bnn()

### ISSUE THREAD

**Issue by barghit** [IntelLabs/bayesian-torch#24]
The problem seems to be in line 544 of conv_flipout.py, the line is self.kl = kl inside the forward() method, i get the error "local variable 'kl' referenced before assignment" as an UnboundLocalError.

Thank you in advance.

**Comment by ranganathkrishnan** [comment]
@barghit can you give more info on how you are defining the model with code snippet or log to understand your issue?

**Comment by barghit** [comment]
Hi! I attached the exact code snippet and the error I get. I don't get the same error with the "Reparameterization" option, it works perfectly. (I also thought it was a problem of the summary method but it does the same when i try to run the training).

[for_github.txt](https://github.com/IntelLabs/bayesian-torch/files/12068925/for_github.txt)

**Comment by ranganathkrishnan** [comment]
fixed with commit 1180b87dc7c0039426d0e41be8c9f52a34db9fc7
