### ISSUE TITLE
modifing the Scripts for any arbitrary output size

### ISSUE THREAD

**Issue by narminGhaffari** [IntelLabs/bayesian-torch#4]
I am trying to use these repo for classification with 3 output nodes. However, in the fully connected layer, I got the error of size mismatch. Can you help me with this issue?

**Comment by ranganathkrishnan** [comment]
Can you give more details, or code snippet of your model? It is not clear what is the issue/error that you are facing.

**Comment by ranganathkrishnan** [comment]
This seem to be related to custom model development and information on the issue is not provided to help further. Closing the issue since no response on requested details.
