### ISSUE TITLE
How bayesian network be used in quantization?

### ISSUE THREAD

**Issue by LeopoldACC** [IntelLabs/bayesian-torch#5]
@peteriz @jpablomch @ranganathkrishnan we can get the $\mu$ and $\sigma$ of each weight ,so how it can be used to quantization which mapping the $w_{float32 }$ into $w_{int8}$

**Comment by ranganathkrishnan** [comment]
@LeopoldACC Quantization of variational parameters in the Bayesian layers is not supported currently.

**Comment by ranganathkrishnan** [comment]
@LeopoldACC  Quantization of Bayesian deep neural network models are supported in the latest release v0.4.0. Please check out!
